{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "collaboration-helper-server.fullname" . }}
  labels:
    {{- include "collaboration-helper-server.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "collaboration-helper-server.fullname" . | quote }}
  http:
    - match:
        - port: {{ .Values.service.apply }}
      route:
        - destination:
            host: {{ include "collaboration-helper-server.fullname" . }}
            port: 
              number: {{ .Values.service.apply }}
            subset: default
{{- end -}}