apiVersion: v1
kind: Service
metadata:
  name: {{ include "collaboration-helper-server.fullname" . }}
  labels:
    {{- include "collaboration-helper-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apply }}
      targetPort: {{ .Values.service.apply }}
      protocol: TCP
      name: grpc-apply
  selector:
    {{- include "collaboration-helper-server.selectorLabels" . | nindent 4 }}
